"""Reading comprehension exercise — read a passage and answer questions.

The passage and questions are generated by the LLM (Claude) at JSON creation
time and passed through via the exercise config.  Falls back to assembling a
passage from database phrases with generic questions when the pre-generated
content is not available.
"""

from __future__ import annotations

import random
from typing import Any

from reportlab.platypus import Flowable, Paragraph, Spacer
from reportlab.lib.units import cm

from langwich.db.models import CEFRLevel, PhraseEntry, VocabularyEntry
from langwich.exercises.base import Exercise, ExerciseContent


class ReadingComprehensionExercise(Exercise):
    """Present a text passage and comprehension questions.

    When the JSON data includes a ``reading`` section (with a coherent
    multi-paragraph passage and deep questions generated by the LLM), those
    are used directly.  Otherwise, the exercise falls back to assembling a
    passage from database phrases with template-based questions.

    Config keys read from the exercise config dict:
      - reading_passage (str): Full passage text from JSON.
      - reading_questions (list[str]): Pre-generated questions from JSON.
      - num_questions (int, default 5): Number of questions to show.
      - max_passage_sentences (int, default 20): Fallback sentence limit.
    """

    @property
    def exercise_type(self) -> str:
        return "reading_comprehension"

    def generate(
        self,
        vocabulary: list[VocabularyEntry],
        phrases: list[PhraseEntry],
        level: CEFRLevel,
    ) -> ExerciseContent:
        num_questions = self.config.get("num_questions", 5)

        # ── Prefer LLM-generated content from the JSON ───────────────
        llm = self.config.get("llm_content")
        passage = (llm or {}).get("passage") or self.config.get("reading_passage") or ""
        questions: list[str] = (llm or {}).get("questions") or self.config.get("reading_questions") or []

        # ── Fallback: assemble passage from phrases ──────────────────
        if not passage:
            passage = self._assemble_fallback_passage(
                phrases,
                self.config.get("max_passage_sentences", 20),
            )

        if not questions:
            questions = self._build_fallback_questions(passage, num_questions)

        questions = questions[:num_questions]
        items = [{"number": i, "question": q} for i, q in enumerate(questions, 1)]

        return ExerciseContent(
            title="Reading Comprehension",
            instructions="Read the passage below carefully, then answer the questions in full sentences.",
            items=items,
            solution=[],
            metadata={"level": level.value, "passage": passage},
        )

    # ── Fallback methods ─────────────────────────────────────────────

    @staticmethod
    def _assemble_fallback_passage(
        phrases: list[PhraseEntry],
        max_sentences: int,
    ) -> str:
        seen: set[str] = set()
        unique: list[PhraseEntry] = []
        for p in phrases:
            if p.text not in seen:
                seen.add(p.text)
                unique.append(p)
        selected = random.sample(unique, min(max_sentences, len(unique)))
        return " ".join(p.text for p in selected)

    @staticmethod
    def _build_fallback_questions(passage: str, num_questions: int) -> list[str]:
        all_words = [w for w in passage.split() if len(w) > 4 and w.isalpha()]
        terms = random.sample(all_words, min(3, len(all_words))) if all_words else []

        questions: list[str] = [
            "What is the main topic of this text? Write 1\u20132 sentences.",
        ]
        if len(terms) >= 1:
            questions.append(
                f"The word \u201c{terms[0]}\u201d appears in the text. "
                f"Explain what it means in this context."
            )
        questions.append("Name two facts or details mentioned in the text.")
        if len(terms) >= 2:
            questions.append(
                f"How does the text connect \u201c{terms[1]}\u201d to the overall topic?"
            )
        questions.append(
            "What is the most important thing you learned from this text? Why?"
        )
        extra = [
            "Summarise the text in 2\u20133 sentences using your own words.",
            "Which sentence in the text do you find most interesting? Explain why.",
            "Write one question you would like to ask the author of this text.",
        ]
        random.shuffle(extra)
        for q in extra:
            if len(questions) >= num_questions:
                break
            questions.append(q)
        return questions[:num_questions]

    def render(self, content: ExerciseContent) -> list[Flowable]:
        from langwich.rendering.styles import body_style, instruction_style
        from langwich.rendering.components import info_box, writing_lines

        flowables: list[Flowable] = []
        flowables.append(Paragraph(content.instructions, instruction_style()))
        flowables.append(Spacer(1, 0.3 * cm))

        # Passage in an info box — min half page height (~350pt on A4)
        passage = content.metadata.get("passage", "")
        flowables.extend(info_box(passage, min_height=350))
        flowables.append(Spacer(1, 0.4 * cm))

        for item in content.items:
            flowables.append(
                Paragraph(f"{item['number']}. {item['question']}", body_style())
            )
            flowables.extend(writing_lines(count=3))
            flowables.append(Spacer(1, 0.2 * cm))

        return flowables
