"""Reusable PDF components — info boxes, writing lines, drawing areas, etc.

All functions return lists of ReportLab ``Flowable`` objects that can be
appended to a PDF story.
"""

from __future__ import annotations

from typing import Any

from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    Flowable,
    HRFlowable,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from langwich.rendering.styles import (
    BORDER_GREY,
    BRAND_ACCENT_SOFT,
    BRAND_DARK,
    BRAND_LIGHT,
    SPACE_SM,
    body_style,
)

# ── Page geometry constants ─────────────────────────────────────────
# A4 usable height after margins (48 pt each) + header/footer (20 pt each).
# Total vertical margin = 2 × (48 + 20) = 136 pt.
# A4 height = 841.89 pt → usable ≈ 705.89 pt.
from reportlab.lib.pagesizes import A4

A4_USABLE_HEIGHT = A4[1] - 2 * (48 + 20)  # ~705.89 pt


class MinHeightFlowable(Flowable):
    """Wrapper that enforces a minimum height on a contained flowable."""

    def __init__(self, child: Flowable, min_height: float) -> None:
        super().__init__()
        self.child = child
        self.min_height = min_height

    def wrap(self, availWidth: float, availHeight: float) -> tuple[float, float]:
        w, h = self.child.wrap(availWidth, availHeight)
        self.width = w
        self.height = max(h, self.min_height)
        return self.width, self.height

    def draw(self) -> None:
        child_height = getattr(self.child, 'height', None) or getattr(self.child, '_height', 0)
        self.child.drawOn(self.canv, 0, self.height - child_height)


def info_box(
    text: str,
    width: float | None = None,
    min_height: float | None = None,
) -> list[Flowable]:
    """Render text inside a rounded, lightly shaded box.

    Used for reading passages, word banks, and informational callouts.

    Parameters
    ----------
    min_height : float | None
        Minimum box height in points. Useful for reading passages that
        should fill a certain portion of the page.
    """
    para = Paragraph(text, body_style())
    table = Table(
        [[para]],
        colWidths=[width or 16 * cm],
    )
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BRAND_LIGHT),
        ("BOX", (0, 0), (-1, -1), 0.75, BORDER_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))

    result: Flowable = table
    if min_height is not None:
        result = MinHeightFlowable(table, min_height)

    return [result, Spacer(1, SPACE_SM)]


def writing_lines(count: int = 3, width: float | None = None) -> list[Flowable]:
    """Render a set of evenly-spaced horizontal writing lines."""
    flowables: list[Flowable] = []
    line_width = width or 16 * cm
    for _ in range(count):
        flowables.append(Spacer(1, 0.6 * cm))
        flowables.append(
            HRFlowable(
                width=line_width,
                thickness=0.5,
                color=BORDER_GREY,
                spaceAfter=2,
            )
        )
    return flowables


def grammar_reference_page(
    level: Any = None,
    target_lang: str = "",
    topic: str | None = None,
    content: str | None = None,
) -> list[Flowable]:
    """Render a grammar reference section with a focus topic.

    Parameters
    ----------
    topic : str | None
        Grammar focus area (e.g. "present tense", "articles").
    content : str | None
        The actual grammar explanation text (rules, examples, tables).
        Generated by the LLM and included in the JSON data.
    """
    from langwich.rendering.styles import subtitle_style, instruction_style

    flowables: list[Flowable] = []
    flowables.append(Paragraph("Grammar Focus", subtitle_style()))

    level_str = level.value if hasattr(level, "value") else str(level) if level else ""
    topic_display = topic or "General"

    flowables.append(
        Paragraph(
            f"Level: {level_str} — Topic: {topic_display}",
            instruction_style(),
        )
    )
    flowables.append(Spacer(1, 0.3 * cm))

    if content:
        flowables.extend(info_box(content, min_height=200))
    elif topic:
        flowables.extend(info_box(topic, min_height=200))
    else:
        flowables.extend(
            info_box(
                "Grammar notes will appear here. Add a \"grammar\" section to "
                "your JSON with \"topic\" and \"content\" fields.",
            )
        )

    flowables.append(Spacer(1, 0.3 * cm))
    return flowables


class DrawingBoxFlowable(Flowable):
    """A bordered rectangular area for drawing/sketching tasks."""

    def __init__(self, width: float, height: float) -> None:
        super().__init__()
        self.width = width
        self.height = height

    def draw(self) -> None:
        self.canv.setStrokeColor(BORDER_GREY)
        self.canv.setLineWidth(0.75)
        self.canv.setFillColor(colors.white)
        self.canv.roundRect(0, 0, self.width, self.height, radius=6, fill=1, stroke=1)


def drawing_box(height_cm: float = 8, width: float | None = None) -> Flowable:
    """Return a bordered drawing area flowable."""
    return DrawingBoxFlowable(
        width=width or 16 * cm,
        height=height_cm * cm,
    )


def vocab_reference_page(
    vocabulary: list[Any],
    source_lang: str = "",
    target_lang: str = "",
    max_entries: int = 30,
) -> list[Flowable]:
    """Render a full vocabulary reference table with terms and translations.

    This is a dedicated vocabulary page placed at the beginning or end of
    the worksheet, listing terms with their translations grouped by part
    of speech.

    Parameters
    ----------
    max_entries : int
        Maximum number of vocabulary rows to display.  Keeps the table
        on a single page even when followed by info boxes.
    """
    import json

    from langwich.rendering.styles import subtitle_style, instruction_style

    flowables: list[Flowable] = []
    flowables.append(Paragraph("Vocabulary", subtitle_style()))
    flowables.append(
        Paragraph(
            "Study these words before starting the exercises. "
            "Cover the right column to test yourself.",
            instruction_style(),
        )
    )
    flowables.append(Spacer(1, 0.3 * cm))

    # Group by part of speech
    from collections import defaultdict

    by_pos: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for entry in vocabulary:
        translations = []
        if entry.translations_json:
            translations = json.loads(entry.translations_json)
        trans_str = ", ".join(translations) if translations else "—"
        pos_label = entry.part_of_speech.value if hasattr(entry.part_of_speech, "value") else str(entry.part_of_speech)
        by_pos[pos_label].append((entry.term, trans_str))

    # Build table rows, respecting the max_entries limit
    from langwich.rendering.styles import BRAND_ACCENT, BRAND_GREY

    table_data = []
    # Header row
    term_label = target_lang.upper() if target_lang else "Term"
    trans_label = source_lang.upper() if source_lang else "Translation"
    table_data.append([term_label, "", trans_label])

    entry_count = 0
    for pos, pairs in sorted(by_pos.items()):
        if entry_count >= max_entries:
            break
        # POS header row
        pos_display = pos.replace("_", " ").title() if pos else "Other"
        table_data.append([Paragraph(f"<b>{pos_display}</b>", body_style()), "", ""])
        for term, trans in sorted(pairs):
            if entry_count >= max_entries:
                break
            table_data.append([term, "→", trans])
            entry_count += 1

    if len(table_data) <= 1:
        return flowables

    table = Table(table_data, colWidths=[7 * cm, 1 * cm, 8 * cm])

    # Style: header row + POS group headers + data rows
    style_commands = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("LEADING", (0, 0), (-1, -1), 14),
        ("TEXTCOLOR", (0, 0), (-1, 0), BRAND_GREY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("LINEBELOW", (0, 0), (-1, 0), 1, BORDER_GREY),
        ("LINEBELOW", (0, 1), (-1, -1), 0.25, BORDER_GREY),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("TEXTCOLOR", (1, 0), (1, -1), BRAND_GREY),
    ]
    table.setStyle(TableStyle(style_commands))
    flowables.append(table)
    return flowables


def ai_upload_recommendation() -> list[Flowable]:
    """Render a styled recommendation box encouraging AI-assisted feedback.

    Placed at the end of the worksheet to remind students they can upload
    their completed work to an AI assistant for instant correction.
    """
    from langwich.rendering.styles import subtitle_style

    flowables: list[Flowable] = []
    flowables.append(Spacer(1, 0.5 * cm))
    flowables.extend(
        info_box(
            "<b>Done?</b> Upload your completed worksheet to an AI assistant "
            "(e.g. ChatGPT, Claude, Gemini) to get instant feedback on your "
            "answers! Take a photo or scan your worksheet and ask the AI to "
            "check your work, explain any mistakes, and suggest improvements.",
        )
    )
    return flowables


def vocab_recommendation_box() -> list[Flowable]:
    """Render a tip box recommending use of vocabulary and grammar.

    Placed on the vocabulary reference page when it appears at the end
    of the worksheet.
    """
    flowables: list[Flowable] = []
    flowables.extend(
        info_box(
            "<b>Tip:</b> Use the vocabulary from this list in your exercises. "
            "Also apply the grammar rules from the grammar reference page! "
            "Try to incorporate as many new words as possible in your written "
            "answers.",
        )
    )
    return flowables


def section_divider() -> list[Flowable]:
    """A thin horizontal rule to separate exercise sections."""
    return [
        Spacer(1, SPACE_SM),
        HRFlowable(width="100%", thickness=1, color=BORDER_GREY, spaceAfter=SPACE_SM),
    ]


# ── Size-aware layout helpers ───────────────────────────────────────

class PageFillerFlowable(Flowable):
    """Invisible spacer that pads content to fill a target height exactly.

    Used to ensure an exercise occupies precisely half / full / double page.
    Wraps a list of child flowables, measures them, then adds blank space so
    that the total height equals ``target_height``.
    """

    def __init__(self, children: list[Flowable], target_height: float) -> None:
        super().__init__()
        self._children = children
        self._target_height = target_height

    def wrap(self, availWidth: float, availHeight: float) -> tuple[float, float]:
        self._avail_width = availWidth
        content_h = 0.0
        for child in self._children:
            w, h = child.wrap(availWidth, availHeight)
            content_h += h
        self.width = availWidth
        self.height = max(content_h, self._target_height)
        return self.width, self.height

    def split(self, availWidth: float, availHeight: float) -> list[Flowable]:
        # Allow ReportLab to page-break within the children normally.
        return self._children

    def draw(self) -> None:
        y = self.height
        for child in self._children:
            w, h = child.wrap(self._avail_width, self.height)
            y -= h
            child.drawOn(self.canv, 0, y)


def target_height_for_size(size: str, usable_height: float | None = None) -> float:
    """Return the target height in points for a ``TaskSize`` value.

    Parameters
    ----------
    size : str
        One of ``"half"``, ``"full"``, ``"double"``.
    usable_height : float | None
        Override for the usable page height (defaults to A4 with standard
        langwich margins).
    """
    h = usable_height or A4_USABLE_HEIGHT
    multipliers = {"half": 0.5, "full": 1.0, "double": 2.0}
    return h * multipliers.get(size, 1.0)
