"""Source text model.

The text is the gold mine: every exercise derives its content from it.
A text can be provided directly or generated by an LLM.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PictureScene:
    """A section of text suitable for image generation."""

    description: str  # English prompt for image generation
    elements: list[str]  # Visual elements that must appear
    paragraph_index: int = 0  # Which paragraph describes the scene


@dataclass
class SourceText:
    """A text that drives exercise generation.

    The text is the central node in the exercise pipeline:
    - FIB: blank out words from the text
    - Picture: generate an image from the picture_scene
    - WordConnections: extract vocabulary from the text
    """

    title: str
    content: str  # Full text in target language
    translation: str  # Full text in source language
    source_lang: str  # ISO 639-1
    target_lang: str  # ISO 639-1
    cefr_level: str  # A1-C2
    topic: str

    picture_scene: PictureScene | None = None

    # Extracted by analysis or provided
    vocabulary: list[dict] = field(default_factory=list)
    # Each: {"term": str, "translation": str, "pos": str}

    @property
    def paragraphs(self) -> list[str]:
        return [p.strip() for p in self.content.split("\n\n") if p.strip()]

    @property
    def picture_paragraph(self) -> str | None:
        if self.picture_scene is None:
            return None
        paragraphs = self.paragraphs
        idx = self.picture_scene.paragraph_index
        if idx < len(paragraphs):
            return paragraphs[idx]
        return None

    def to_dict(self) -> dict:
        d = {
            "title": self.title,
            "content": self.content,
            "translation": self.translation,
            "source_lang": self.source_lang,
            "target_lang": self.target_lang,
            "cefr_level": self.cefr_level,
            "topic": self.topic,
            "vocabulary": self.vocabulary,
        }
        if self.picture_scene:
            d["picture_scene"] = {
                "description": self.picture_scene.description,
                "elements": self.picture_scene.elements,
                "paragraph_index": self.picture_scene.paragraph_index,
            }
        return d

    @classmethod
    def from_dict(cls, data: dict) -> SourceText:
        scene = None
        if "picture_scene" in data:
            ps = data["picture_scene"]
            scene = PictureScene(
                description=ps["description"],
                elements=ps["elements"],
                paragraph_index=ps.get("paragraph_index", 0),
            )
        return cls(
            title=data["title"],
            content=data["content"],
            translation=data["translation"],
            source_lang=data["source_lang"],
            target_lang=data["target_lang"],
            cefr_level=data["cefr_level"],
            topic=data["topic"],
            picture_scene=scene,
            vocabulary=data.get("vocabulary", []),
        )
